# Generated by Django 5.0.14 on 2025-04-16 04:30

import correspondencia.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='Sin nombre', max_length=150)),
                ('apellidos', models.CharField(blank=True, max_length=150, null=True)),
                ('cargo', models.CharField(blank=True, help_text='Cargo del contacto dentro de la entidad (opcional)', max_length=150, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono del Contacto')),
            ],
            options={
                'verbose_name': 'Contacto Externo',
                'verbose_name_plural': 'Contactos Externos',
                'ordering': ['entidad_externa__nombre', 'apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='EntidadExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo de la entidad externa', max_length=255, unique=True)),
                ('nit', models.CharField(blank=True, help_text='NIT o identificador fiscal (opcional)', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Entidad Externa',
                'verbose_name_plural': 'Entidades Externas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CorreoEntrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Message-ID único del correo', max_length=255, unique=True)),
                ('remitente', models.EmailField(max_length=254)),
                ('asunto', models.CharField(blank=True, max_length=500)),
                ('cuerpo_texto', models.TextField(blank=True, help_text='Cuerpo del mensaje en texto plano')),
                ('cuerpo_html', models.TextField(blank=True, help_text='Cuerpo del mensaje en HTML (si existe)')),
                ('fecha_recepcion_original', models.DateTimeField(blank=True, help_text="Fecha del encabezado 'Date' del correo", null=True)),
                ('fecha_lectura_imap', models.DateTimeField(default=django.utils.timezone.now)),
                ('procesado', models.BooleanField(db_index=True, default=False, help_text='Indica si ya se intentó la clasificación IA')),
                ('requiere_revision_manual', models.BooleanField(default=False, help_text='Marcar si la radicación automática falló y necesita intervención.')),
                ('fecha_clasificacion', models.DateTimeField(blank=True, help_text='Fecha y hora en que se realizó la clasificación IA', null=True)),
                ('oficina_clasificada', models.ForeignKey(blank=True, help_text='Oficina destino predicha por IA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_clasificados_oficina', to='documentos.oficinaproductora')),
                ('serie_clasificada', models.ForeignKey(blank=True, help_text='Serie documental predicha por IA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_clasificados_serie', to='documentos.seriedocumental')),
                ('subserie_clasificada', models.ForeignKey(blank=True, help_text='Subserie documental predicha por IA (relacionada a la serie)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_clasificados_subserie', to='documentos.subseriedocumental')),
            ],
            options={
                'verbose_name': 'Correo Entrante IMAP',
                'verbose_name_plural': 'Correos Entrantes IMAP',
                'ordering': ['-fecha_lectura_imap'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoCorreoEntrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=255, upload_to=correspondencia.models.ruta_adjunto_correo_entrante)),
                ('nombre_original', models.CharField(blank=True, help_text='Nombre original del archivo en el correo', max_length=255)),
                ('tipo_mime', models.CharField(blank=True, help_text='Tipo MIME detectado del archivo', max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('correo_entrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='correspondencia.correoentrante')),
            ],
            options={
                'verbose_name': 'Adjunto de Correo Entrante',
                'verbose_name_plural': 'Adjuntos de Correo Entrante',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_radicado', models.CharField(editable=False, max_length=50, unique=True)),
                ('tipo_radicado', models.CharField(choices=[('ENTRANTE', 'Entrante')], default='ENTRANTE', max_length=20)),
                ('fecha_radicacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('asunto', models.TextField()),
                ('medio_recepcion', models.CharField(choices=[('FISICO', 'Físico'), ('ELECTRONICO', 'Electrónico')], max_length=20)),
                ('requiere_respuesta', models.BooleanField(default=False)),
                ('tiempo_respuesta', models.CharField(blank=True, choices=[('NORMAL', 'Normal (15 días hábiles)'), ('URGENTE', 'Urgente (5 días hábiles)'), ('MUY_URGENTE', 'Muy Urgente (3 días hábiles)')], max_length=20, null=True)),
                ('estado', models.CharField(choices=[('RADICADA', 'Radicada'), ('ASIGNADA_USUARIO', 'Asignada a Usuario'), ('DISTRIBUIDA_OFICINA', 'Distribuida a Oficina'), ('LEIDA', 'Leída'), ('REDISTRIBUIDA_INTERNA', 'Redistribuida Internamente'), ('CON_RESPUESTA_PENDIENTE', 'Con Respuesta Pendiente')], default='RADICADA', max_length=30)),
                ('leido_por_oficina', models.BooleanField(default=False, help_text='Indica si alguien de la oficina destino ya lo leyó')),
                ('resumen_ia', models.TextField(blank=True, help_text='Resumen del contenido generado por IA', null=True)),
                ('oficina_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correspondencia_recibida', to='documentos.oficinaproductora')),
                ('remitente', models.ForeignKey(blank=True, help_text='Seleccione el contacto (persona) que envía', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencias_enviadas', to='correspondencia.contacto')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.seriedocumental')),
                ('subserie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.subseriedocumental')),
                ('usuario_destino_inicial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencia_asignada_directa', to=settings.AUTH_USER_MODEL)),
                ('usuario_radicador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencia_radicada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correspondencia',
                'verbose_name_plural': 'Correspondencias',
                'ordering': ['-fecha_radicacion'],
            },
        ),
        migrations.AddField(
            model_name='correoentrante',
            name='radicado_asociado',
            field=models.ForeignKey(blank=True, help_text='Correspondencia creada a partir de este correo (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correo_origen', to='correspondencia.correspondencia'),
        ),
        migrations.CreateModel(
            name='AdjuntoCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=255, upload_to=correspondencia.models.ruta_adjunto_correo)),
                ('nombre_original', models.CharField(blank=True, help_text='Nombre original del archivo en el correo', max_length=255)),
                ('tipo_mime', models.CharField(blank=True, help_text='Tipo MIME detectado del archivo', max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_correo', to='correspondencia.correspondencia')),
            ],
            options={
                'verbose_name': 'Adjunto de Correo',
                'verbose_name_plural': 'Adjuntos de Correo',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='entidad_externa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='correspondencia.entidadexterna', verbose_name='Entidad Externa'),
        ),
        migrations.CreateModel(
            name='HistorialCorrespondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento', models.CharField(choices=[('RADICADA', 'Radicada'), ('ASIGNADA_USUARIO', 'Asignada a Usuario'), ('DISTRIBUIDA_OFICINA', 'Distribuida a Oficina'), ('LEIDA', 'Leída'), ('REDISTRIBUIDA_INTERNA', 'Redistribuida Internamente'), ('CON_RESPUESTA_PENDIENTE', 'Con Respuesta Pendiente')], max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='correspondencia.correspondencia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_correspondencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Correspondencia',
                'verbose_name_plural': 'Historiales de Correspondencia',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DistribucionInternaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('leido', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones_internas', to='correspondencia.correspondencia')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondencia_asignada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distribución Interna',
                'verbose_name_plural': 'Distribuciones Internas',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('correspondencia', 'usuario_asignado')},
            },
        ),
        migrations.AddConstraint(
            model_name='contacto',
            constraint=models.UniqueConstraint(fields=('entidad_externa', 'nombres', 'apellidos', 'correo_electronico'), name='contacto_unico_por_entidad'),
        ),
    ]
