# Generated by Django 5.0.14 on 2025-04-17 23:24

import correspondencia.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondenciaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_radicado_salida', models.CharField(editable=False, max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('destinatario_email', models.EmailField(editable=False, help_text='Email del destinatario al momento de la aprobación (automático).', max_length=254)),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION', 'Pendiente Aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ENVIADA', 'Enviada'), ('ERROR_ENVIO', 'Error de Envío')], default='BORRADOR', max_length=30)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('id_mensaje_enviado', models.CharField(blank=True, max_length=255, null=True)),
                ('destinatario_contacto', models.ForeignKey(editable=False, help_text='Contacto externo al que se dirige la respuesta (automático).', on_delete=django.db.models.deletion.PROTECT, related_name='correspondencia_recibida_saliente', to='correspondencia.contacto')),
                ('respuesta_a', models.ForeignKey(help_text='Correspondencia entrante a la que responde este documento.', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_salientes', to='correspondencia.correspondencia')),
                ('usuario_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencia_aprobada', to=settings.AUTH_USER_MODEL)),
                ('usuario_redactor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencia_redactada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correspondencia de Salida',
                'verbose_name_plural': 'Correspondencias de Salida',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=255, upload_to=correspondencia.models.ruta_adjunto_salida)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('correspondencia_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='correspondencia.correspondenciasalida')),
            ],
            options={
                'verbose_name': 'Adjunto de Salida',
                'verbose_name_plural': 'Adjuntos de Salida',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='HistorialSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_evento', models.CharField(choices=[('CREACION', 'Creación Borrador'), ('MODIFICACION', 'Modificación Borrador'), ('ENVIO_APROBACION', 'Enviado a Aprobación'), ('APROBACION', 'Aprobado por Ventanilla'), ('RECHAZO', 'Rechazado por Ventanilla'), ('INTENTO_ENVIO', 'Intento de Envío Email'), ('ENVIO_EXITOSO', 'Email Enviado Exitosamente'), ('ENVIO_FALLIDO', 'Error al Enviar Email')], max_length=30)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales, motivo rechazo, error envío...', null=True)),
                ('correspondencia_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='correspondencia.correspondenciasalida')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Correspondencia Salida',
                'verbose_name_plural': 'Historiales de Correspondencia Salida',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
