# Generated by Django 5.0.14 on 2025-06-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_correspondenciasalida_adjuntosalida_historialsalida'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadexterna',
            name='dominio',
            field=models.CharField(blank=True, help_text='Dominio de correo asociado (opcional)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('RADICADA', 'Radicada'), ('ASIGNADA_USUARIO', 'Asignada a Usuario'), ('LEIDA', 'Leída por Oficina'), ('RESPONDIDA', 'Respondida')], default='RADICADA', max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='medio_recepcion',
            field=models.CharField(choices=[('FISICO', 'Físico'), ('ELECTRONICO', 'Electrónico')], default='FISICO', max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION', 'Pendiente Aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ENVIADA', 'Enviada'), ('ERROR_ENVIO', 'Error de Envío')], default='BORRADOR', max_length=50),
        ),
        migrations.AlterField(
            model_name='historialcorrespondencia',
            name='evento',
            field=models.CharField(choices=[('RADICADA', 'Radicada'), ('ASIGNADA_USUARIO', 'Asignada a Usuario'), ('LEIDA', 'Leída por Oficina'), ('RESPONDIDA', 'Respondida')], max_length=30),
        ),
    ]
