# Generated by Django 5.0.14 on 2025-08-10 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_entidadexterna_dominio_alter_correspondencia_estado_and_more'),
        ('documentos', '0002_perfilusuario_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True)),
                ('es_habil', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Día laboral',
                'verbose_name_plural': 'Calendario laboral',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='TramiteTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('plazo_dias_habiles', models.PositiveSmallIntegerField()),
                ('fundamento_normativo', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de trámite',
                'verbose_name_plural': 'Tipos de trámite',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SubserieTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subserie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tramite_map', to='documentos.subseriedocumental')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subseries', to='correspondencia.tramitetipo')),
            ],
            options={
                'verbose_name': 'Trámite por subserie',
                'verbose_name_plural': 'Trámites por subserie',
            },
        ),
    ]
