# Generated by Django 5.0.14 on 2025-08-12 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0004_calendariolaboral_tramitetipo_subserietramite'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='fecha_limite_respuesta_persist',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='plazo_origen',
            field=models.CharField(choices=[('TRD', 'TRD (Trámite por Subserie)'), ('FALLBACK', 'Configuración (Tiempo de Respuesta)'), ('NONE', 'No Aplica')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='plazo_respuesta_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='tramite_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='correspondencia.tramitetipo'),
        ),
    ]
