# Generated by Django 5.0.14 on 2025-08-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0005_correspondencia_fecha_limite_respuesta_persist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='fecha_sellado',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del primer sellado', null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='sellado',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si el documento físico ya fue sellado/imprimido'),
        ),
    ]
