# Generated by Django 5.0.14 on 2025-08-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0006_correspondencia_fecha_sellado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nombres',
            field=models.CharField(max_length=150),
        ),
    ]
