# Generated by Django 5.0.14 on 2025-08-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0007_alter_contacto_nombres'),
    ]

    operations = [
    ]
