# Generated by Django 5.0.14 on 2025-08-28 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0008_auto_20250821_2253'),
        ('documentos', '0002_perfilusuario_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_snapshot', models.EmailField(max_length=254)),
                ('nombre_snapshot', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLO', 'Fallo')], default='PENDIENTE', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('id_mensaje_enviado', models.CharField(blank=True, max_length=255, null=True)),
                ('detalle_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Destinatario de Salida',
                'verbose_name_plural': 'Destinatarios de Salida',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='contacto',
            name='contacto_unico_por_entidad',
        ),
        migrations.AddField(
            model_name='contacto',
            name='oficina_propietaria',
            field=models.ForeignKey(blank=True, help_text='Oficina propietaria de este contacto (agenda por oficina)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos_oficina', to='documentos.oficinaproductora'),
        ),
        migrations.AddField(
            model_name='correspondenciasalida',
            name='oficina_emisora',
            field=models.ForeignKey(editable=False, help_text='Oficina emisora de la correspondencia de salida (derivada de la entrante)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_emitidas', to='documentos.oficinaproductora'),
        ),
        migrations.AddField(
            model_name='correspondenciasalida',
            name='oficina_emisora_nombre',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciasalida',
            name='redactor_cargo',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciasalida',
            name='redactor_nombre',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='contacto',
            constraint=models.UniqueConstraint(fields=('oficina_propietaria', 'entidad_externa', 'nombres', 'apellidos', 'correo_electronico'), name='contacto_unico_en_oficina'),
        ),
        migrations.AddField(
            model_name='salidadestinatario',
            name='contacto',
            field=models.ForeignKey(help_text='Contacto destinatario (debe pertenecer a la oficina emisora)', on_delete=django.db.models.deletion.PROTECT, related_name='destinatario_en_salidas', to='correspondencia.contacto'),
        ),
        migrations.AddField(
            model_name='salidadestinatario',
            name='correspondencia_salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='correspondencia.correspondenciasalida'),
        ),
    ]
