# Generated by Django 5.0.14 on 2025-08-28 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0009_salidadestinatario_and_more'),
        ('documentos', '0002_perfilusuario_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicacionMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('PARCIAL', 'Enviada Parcialmente'), ('ERROR', 'Error General de Envío')], default='BORRADOR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('oficina_emisora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicaciones_masivas', to='documentos.oficinaproductora')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicación Masiva',
                'verbose_name_plural': 'Comunicaciones Masivas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComunicacionDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_snapshot', models.EmailField(max_length=254)),
                ('nombre_snapshot', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLO', 'Fallo')], default='PENDIENTE', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('id_mensaje_enviado', models.CharField(blank=True, max_length=255, null=True)),
                ('detalle_error', models.TextField(blank=True, null=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicaciones_recibidas', to='correspondencia.contacto')),
                ('comunicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='correspondencia.comunicacionmasiva')),
            ],
            options={
                'verbose_name': 'Destinatario de Comunicación',
                'verbose_name_plural': 'Destinatarios de Comunicación',
                'ordering': ['id'],
                'unique_together': {('comunicacion', 'contacto')},
            },
        ),
        migrations.CreateModel(
            name='GrupoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contactos', models.ManyToManyField(blank=True, related_name='grupos_agenda', to='correspondencia.contacto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oficina_propietaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_agenda', to='documentos.oficinaproductora')),
            ],
            options={
                'verbose_name': 'Grupo de Agenda',
                'verbose_name_plural': 'Grupos de Agenda',
                'ordering': ['nombre'],
                'unique_together': {('oficina_propietaria', 'nombre')},
            },
        ),
    ]
