# Generated by Django 5.0.14 on 2025-09-01 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0010_comunicacionmasiva_comunicaciondestinatario_and_more'),
        ('documentos', '0002_perfilusuario_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal (#RRGGBB)', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oficina_propietaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_contactos', to='documentos.oficinaproductora')),
            ],
            options={
                'verbose_name': 'Categoría de Contacto',
                'verbose_name_plural': 'Categorías de Contactos',
                'ordering': ['nombre'],
                'unique_together': {('oficina_propietaria', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Categorías a las que pertenece este contacto', related_name='contactos', to='correspondencia.categoriacontacto'),
        ),
    ]
