# Generated by Django 5.0.14 on 2025-09-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0011_categoriacontacto_contacto_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='CategoriaContacto',
        ),
    ]
