# Generated by Django 5.0.14 on 2025-09-02 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0012_remove_contacto_categorias_delete_categoriacontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciasalida',
            name='envio_detalle_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciasalida',
            name='envio_grupo',
            field=models.ForeignKey(blank=True, help_text='Grupo/Categoría utilizado para el envío cuando aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_asociadas', to='correspondencia.grupoagenda'),
        ),
        migrations.AddField(
            model_name='correspondenciasalida',
            name='envio_tipo',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual/Dirigido'), ('GRUPO', 'Grupo/Categoría'), ('MULTIPLE_SELECTIVO', 'Selección múltiple')], help_text='Modalidad de envío registrada al crear la salida. Opcional para trazabilidad.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciasalida',
            name='envio_total_destinatarios',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
