# Generated by Django 5.0.14 on 2025-09-06 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0013_correspondenciasalida_envio_detalle_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='respuesta_a',
            field=models.ForeignKey(blank=True, help_text='Correspondencia entrante a la que responde este documento (opcional para salidas independientes).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_salientes', to='correspondencia.correspondencia'),
        ),
    ]
