# Generated by Django 5.0.14 on 2025-09-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0014_alter_correspondenciasalida_respuesta_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidadestinatario',
            name='dsn_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salidadestinatario',
            name='smtp_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salidadestinatario',
            name='ultimo_evento_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comunicaciondestinatario',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLO', 'Fallo'), ('REBOTE', 'Rebote')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='salidadestinatario',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLO', 'Fallo'), ('REBOTE', 'Rebote')], default='PENDIENTE', max_length=20),
        ),
    ]
