# Generated by Django 5.0.14 on 2025-10-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0015_salidadestinatario_dsn_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucioninternausuario',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se marcó como leído', null=True),
        ),
    ]
