# Generated by Django 5.0.14 on 2025-11-10 01:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0018_contacto_numero_documento'),
        ('documentos', '0003_nacionalidad_tipodocumento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcorrespondencia',
            name='evento',
            field=models.CharField(choices=[('RADICADA', 'Radicada'), ('ASIGNADA_USUARIO', 'Asignada a Usuario'), ('LEIDA', 'Leída por Oficina'), ('RESPONDIDA', 'Respondida'), ('SELLO_IMPRESO', 'Sello impreso'), ('REDISTRIBUIDA_INTERNA', 'Redistribuida internamente'), ('COMPARTIDA_OFICINA', 'Compartida con oficina')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('asignacion', 'Nueva Asignación'), ('compartido', 'Correspondencia Compartida'), ('respuesta', 'Nueva Respuesta'), ('vencimiento', 'Próximo a Vencer'), ('acceso_oficina', 'Acceso para otra oficina'), ('otro', 'Otro')], default='asignacion', max_length=20),
        ),
        migrations.CreateModel(
            name='AccesoCorrespondenciaOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compartido', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('leido', models.BooleanField(default=False, help_text='Indica si la oficina abrió por primera vez el detalle.')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('compartido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_interoficina_creados', to=settings.AUTH_USER_MODEL)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_oficinas', to='correspondencia.correspondencia')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondencias_con_acceso', to='documentos.oficinaproductora')),
            ],
            options={
                'verbose_name': 'Acceso de Oficina a Correspondencia',
                'verbose_name_plural': 'Accesos de Oficinas a Correspondencias',
                'ordering': ['-fecha_compartido'],
            },
        ),
        migrations.AddConstraint(
            model_name='accesocorrespondenciaoficina',
            constraint=models.UniqueConstraint(fields=('correspondencia', 'oficina'), name='unique_correspondencia_oficina_acceso'),
        ),
    ]
