# Generated by Django 5.0.14 on 2025-11-15 01:19

import django.db.models.deletion
from django.db import migrations, models


def marcar_contactos_globales(apps, schema_editor):
    Contacto = apps.get_model('correspondencia', 'Contacto')
    Contacto.objects.filter(oficina_propietaria__isnull=True).update(es_global=True)


def enlazar_contactos_oficina(apps, schema_editor):
    Contacto = apps.get_model('correspondencia', 'Contacto')
    globales = Contacto.objects.filter(
        es_global=True,
        correo_electronico__isnull=False
    ).values('id', 'correo_electronico')

    mapa_global = {
        (item['correo_electronico'] or '').strip().lower(): item['id']
        for item in globales
        if item['correo_electronico']
    }

    contactos_oficina = Contacto.objects.filter(
        es_global=False,
        correo_electronico__isnull=False
    ).values('id', 'correo_electronico')

    for contacto in contactos_oficina:
        correo = (contacto['correo_electronico'] or '').strip().lower()
        contacto_global_id = mapa_global.get(correo)
        if contacto_global_id:
            Contacto.objects.filter(id=contacto['id']).update(contacto_global_id=contacto_global_id)


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0020_contacto_correo_unico'),
        ('documentos', '0003_nacionalidad_tipodocumento_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contacto',
            name='contacto_unico_en_oficina',
        ),
        migrations.RemoveConstraint(
            model_name='contacto',
            name='contacto_correo_oficina_unico',
        ),
        migrations.AddField(
            model_name='contacto',
            name='contacto_global',
            field=models.ForeignKey(blank=True, help_text='Contacto global asociado a este registro de oficina.', limit_choices_to=models.Q(('es_global', True)), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variantes_oficina', to='correspondencia.contacto'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='es_global',
            field=models.BooleanField(default=False, help_text='Indica si el contacto pertenece a la agenda global (Ventanilla).'),
        ),
        migrations.RunPython(marcar_contactos_globales, migrations.RunPython.noop),
        migrations.RunPython(enlazar_contactos_oficina, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='contacto',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('contacto_global__isnull', True), ('es_global', True), ('oficina_propietaria__isnull', True)), models.Q(('es_global', False), ('oficina_propietaria__isnull', False)), _connector='OR'), name='contacto_coherencia_tipo'),
        ),
        migrations.AddConstraint(
            model_name='contacto',
            constraint=models.UniqueConstraint(condition=models.Q(('correo_electronico__isnull', False), ('es_global', True)), fields=('correo_electronico',), name='contacto_correo_global_unico'),
        ),
        migrations.AddConstraint(
            model_name='contacto',
            constraint=models.UniqueConstraint(condition=models.Q(('correo_electronico__isnull', False), ('es_global', False)), fields=('oficina_propietaria', 'correo_electronico'), name='contacto_correo_oficina_unico'),
        ),
        migrations.AddConstraint(
            model_name='contacto',
            constraint=models.UniqueConstraint(condition=models.Q(('es_global', False)), fields=('oficina_propietaria', 'entidad_externa', 'nombres', 'apellidos', 'correo_electronico'), name='contacto_unico_en_oficina'),
        ),
    ]
