# Generated by Django 5.0.14 on 2025-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0021_remove_contacto_contacto_unico_en_oficina_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contacto',
            name='contacto_coherencia_tipo',
        ),
        migrations.RemoveConstraint(
            model_name='contacto',
            name='contacto_correo_global_unico',
        ),
        migrations.RemoveConstraint(
            model_name='contacto',
            name='contacto_correo_oficina_unico',
        ),
        migrations.RemoveConstraint(
            model_name='contacto',
            name='contacto_unico_en_oficina',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='contacto_global',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='es_global',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='oficina_propietaria',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
