# Generated by Django 5.0.14 on 2025-12-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0022_remove_contacto_contacto_coherencia_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesocorrespondenciaoficina',
            name='solo_lider',
            field=models.BooleanField(default=True, help_text="Si es True, solo los usuarios del grupo 'Lider' de la oficina podrán ver esto."),
        ),
    ]
