# Generated by Django 5.2.1 on 2025-12-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0023_accesocorrespondenciaoficina_solo_lider'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesocorrespondenciaoficina',
            name='puede_responder',
            field=models.BooleanField(default=False, help_text='Indica si esta oficina externa tiene permiso para generar respuestas.'),
        ),
    ]
