# Generated by Django 5.0.14 on 2025-12-11 21:12

import correspondencia.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0024_accesocorrespondenciaoficina_puede_responder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeDiarioCorrespondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del informe (un informe por día)', unique=True)),
                ('archivo_firmado', models.FileField(blank=True, help_text='Archivo escaneado con las firmas', null=True, upload_to=correspondencia.models.ruta_informe_firmado)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Firma'), ('FIRMADO', 'Firmado')], default='PENDIENTE', max_length=20)),
                ('total_correspondencias', models.IntegerField(default=0, help_text='Total de correspondencias del día')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_subida_firma', models.DateTimeField(blank=True, null=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe Diario de Correspondencia',
                'verbose_name_plural': 'Informes Diarios de Correspondencia',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDescargaInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descargas_informes', to=settings.AUTH_USER_MODEL)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas', to='correspondencia.informediariocorrespondencia')),
            ],
            options={
                'verbose_name': 'Historial de Descarga',
                'verbose_name_plural': 'Historial de Descargas',
                'ordering': ['-fecha_descarga'],
            },
        ),
    ]
