# Generated by Django 5.2.1 on 2025-12-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0025_informes_diarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='en_planilla',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si esta correspondencia ya fue descargada e incluida en una planilla'),
        ),
    ]
