# Generated by Django 5.0.14 on 2025-12-17 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0026_agregar_campo_en_planilla'),
        ('documentos', '0009_add_notificacion_aviso_prestamo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicacionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.CharField(default='Saravena', max_length=100)),
                ('fecha_documento', models.DateField(help_text='Fecha que aparecerá en el documento impreso')),
                ('remitente_nombre', models.CharField(max_length=255)),
                ('remitente_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField(help_text='Contenido principal de la comunicación')),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='interna/generados/')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada / Radicada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('destinatario_oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internas_recibidas', to='documentos.oficinaproductora')),
                ('destinatario_usuario', models.ForeignKey(blank=True, help_text='Opcional: Si va dirigido a una persona específica', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('remitente_oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internas_enviadas', to='documentos.oficinaproductora')),
                ('remitente_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicación Interna',
                'verbose_name_plural': 'Comunicaciones Internas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
