# Generated by Django 5.0.14 on 2025-12-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0027_comunicacioninterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacioninterna',
            name='trd',
            field=models.CharField(blank=True, help_text='Código TRD (Tabla de Retención Documental)', max_length=100, null=True),
        ),
    ]
