# Generated by Django 5.0.14 on 2025-12-18 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0028_comunicacioninterna_trd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacioninterna',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de revisión/aprobación', null=True),
        ),
        migrations.AddField(
            model_name='comunicacioninterna',
            name='revisado_cargo',
            field=models.CharField(blank=True, help_text='Cargo del revisor (snapshot)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comunicacioninterna',
            name='revisado_nombre',
            field=models.CharField(blank=True, help_text='Nombre del revisor (snapshot)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comunicacioninterna',
            name='revisado_por',
            field=models.ForeignKey(blank=True, help_text='Líder de oficina que revisó y aprobó la comunicación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicaciones_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicacioninterna',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('ENVIADA', 'Enviada / Radicada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20),
        ),
    ]
