# Generated by Django 5.0.14 on 2025-12-19 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0029_comunicacioninterna_fecha_revision_and_more'),
        ('documentos', '0009_add_notificacion_aviso_prestamo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacioninterna',
            name='archivo_firmado',
            field=models.FileField(blank=True, help_text='PDF firmado digitalmente por el líder (requerido para distribución a toda la entidad)', null=True, upload_to='interna/firmados/'),
        ),
        migrations.AddField(
            model_name='comunicacioninterna',
            name='comunicacion_origen',
            field=models.ForeignKey(blank=True, help_text='Comunicación original a la que responde (solo 1 respuesta permitida por comunicación)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='correspondencia.comunicacioninterna'),
        ),
        migrations.AddField(
            model_name='comunicacioninterna',
            name='es_a_toda_entidad',
            field=models.BooleanField(default=False, help_text='Si es True, va a todos los usuarios del sistema y requiere firma digital.'),
        ),
        migrations.AddField(
            model_name='comunicacioninterna',
            name='fecha_distribucion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de distribución', null=True),
        ),
        migrations.AddField(
            model_name='comunicacioninterna',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se subió el archivo firmado', null=True),
        ),
        migrations.AddField(
            model_name='comunicacioninterna',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Motivo del rechazo (si aplica)', null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='comunicacion_interna',
            field=models.ForeignKey(blank=True, help_text='Comunicación interna asociada (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='correspondencia.comunicacioninterna'),
        ),
        migrations.AlterField(
            model_name='comunicacioninterna',
            name='destinatario_oficina',
            field=models.ForeignKey(blank=True, help_text='Oficina destino. Dejar vacío si es a toda la entidad.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internas_recibidas', to='documentos.oficinaproductora'),
        ),
        migrations.AlterField(
            model_name='comunicacioninterna',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('RECHAZADA', 'Rechazada'), ('APROBADA', 'Aprobada (Pendiente Firma/Distribución)'), ('DISTRIBUIDA', 'Distribuida'), ('RESPONDIDA', 'Respondida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=25),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('asignacion', 'Nueva Asignación'), ('compartido', 'Correspondencia Compartida'), ('respuesta', 'Nueva Respuesta'), ('vencimiento', 'Próximo a Vencer'), ('acceso_oficina', 'Acceso para otra oficina'), ('comunicacion_interna', 'Comunicación Interna'), ('aprobacion_pendiente', 'Aprobación Pendiente'), ('otro', 'Otro')], default='asignacion', max_length=25),
        ),
        migrations.CreateModel(
            name='HistorialComunicacionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('CREADA', 'Comunicación Creada'), ('ENVIADA_APROBACION', 'Enviada a Aprobación'), ('APROBADA', 'Aprobada por Líder'), ('RECHAZADA', 'Rechazada por Líder'), ('FIRMA_SUBIDA', 'Firma Digital Subida'), ('DISTRIBUIDA', 'Distribuida a Destinatarios'), ('LEIDA', 'Leída por Usuario'), ('RESPUESTA_CREADA', 'Respuesta Creada'), ('ANULADA', 'Comunicación Anulada')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del evento', null=True)),
                ('comunicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='correspondencia.comunicacioninterna')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_comunicaciones_internas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Comunicación Interna',
                'verbose_name_plural': 'Historiales de Comunicaciones Internas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ComunicacionInternaDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_distribucion', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('comunicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='correspondencia.comunicacioninterna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_internas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distribución de Comunicación Interna',
                'verbose_name_plural': 'Distribuciones de Comunicaciones Internas',
                'ordering': ['-fecha_distribucion'],
                'unique_together': {('comunicacion', 'usuario')},
            },
        ),
    ]
