# Generated by Django 5.0.14 on 2025-12-21 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0030_comunicacioninterna_archivo_firmado_and_more'),
        ('documentos', '0011_macroproceso_proceso_oficinaproductora_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacioninterna',
            name='destinatario_proceso',
            field=models.ForeignKey(blank=True, help_text="Proceso destino (solo cuando tipo_distribucion = 'PROCESO')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunicaciones_internas', to='documentos.proceso'),
        ),
        migrations.AddField(
            model_name='comunicacioninterna',
            name='tipo_distribucion',
            field=models.CharField(blank=True, choices=[('USUARIO', 'Usuario Específico'), ('OFICINA', 'Oficina Completa (Subproceso)'), ('PROCESO', 'Proceso Completo'), ('ENTIDAD', 'Toda la Entidad')], default='USUARIO', help_text='Tipo de distribución de la comunicación', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comunicacioninterna',
            name='archivo_firmado',
            field=models.FileField(blank=True, help_text='PDF firmado digitalmente por el líder (requerido para distribución a oficina/proceso/entidad)', null=True, upload_to='interna/firmados/'),
        ),
        migrations.AlterField(
            model_name='comunicacioninterna',
            name='es_a_toda_entidad',
            field=models.BooleanField(default=False, help_text="Si es True, va a todos los usuarios del sistema y requiere firma digital. (DEPRECADO: usar tipo_distribucion='ENTIDAD')"),
        ),
    ]
