# Generated by Django 5.2.1 on 2025-12-23 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0031_comunicacioninterna_destinatario_proceso_and_more'),
        ('documentos', '0011_macroproceso_proceso_oficinaproductora_proceso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicacionInternaDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('USUARIO', 'Usuario'), ('OFICINA', 'Oficina')], help_text='Tipo de destinatario: Usuario específico o Oficina completa', max_length=10)),
            ],
            options={
                'verbose_name': 'Destinatario de Comunicación Interna',
                'verbose_name_plural': 'Destinatarios de Comunicaciones Internas',
                'ordering': ['tipo', 'oficina', 'usuario'],
            },
        ),
        migrations.AddConstraint(
            model_name='comunicacioninterna',
            constraint=models.UniqueConstraint(condition=models.Q(('comunicacion_origen__isnull', False)), fields=('comunicacion_origen',), name='unique_respuesta_por_comunicacion', violation_error_message='Solo se permite una respuesta por comunicación.'),
        ),
        migrations.AddField(
            model_name='comunicacioninternadestinatario',
            name='comunicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios_multiples', to='correspondencia.comunicacioninterna'),
        ),
        migrations.AddField(
            model_name='comunicacioninternadestinatario',
            name='oficina',
            field=models.ForeignKey(blank=True, help_text="Oficina destinataria (si tipo='OFICINA')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_internas_destinatario', to='documentos.oficinaproductora'),
        ),
        migrations.AddField(
            model_name='comunicacioninternadestinatario',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text="Usuario destinatario (si tipo='USUARIO')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_internas_destinatario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='comunicacioninternadestinatario',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('oficina__isnull', True), ('tipo', 'USUARIO'), ('usuario__isnull', False)), models.Q(('oficina__isnull', False), ('tipo', 'OFICINA'), ('usuario__isnull', True)), _connector='OR'), name='destinatario_tipo_valido'),
        ),
        migrations.AlterUniqueTogether(
            name='comunicacioninternadestinatario',
            unique_together={('comunicacion', 'oficina'), ('comunicacion', 'usuario')},
        ),
    ]
