# Generated by Django 5.2.1 on 2025-12-24 17:28

import correspondencia.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0032_agregar_destinatarios_multiples_comunicacion_interna'),
        ('documentos', '0013_alter_perfilusuario_options_perfilusuario_direccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaCorrespondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_imagen', models.ImageField(help_text='Imagen de la firma digital capturada', upload_to=correspondencia.models.ruta_firma_correspondencia)),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('nombre_firmante', models.CharField(help_text='Nombre del funcionario que firmó (snapshot)', max_length=255)),
                ('cargo_firmante', models.CharField(blank=True, help_text='Cargo del firmante (snapshot)', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('correspondencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_recibida', to='correspondencia.correspondencia')),
                ('firmado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que firmó (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencias_firmadas', to=settings.AUTH_USER_MODEL)),
                ('oficina_firmante', models.ForeignKey(blank=True, help_text='Oficina del firmante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_recibidas', to='documentos.oficinaproductora')),
                ('recolector', models.ForeignKey(help_text='Usuario que recolectó la firma', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_recolectadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firma de Correspondencia',
                'verbose_name_plural': 'Firmas de Correspondencias',
                'ordering': ['-fecha_firma'],
            },
        ),
    ]
