# Generated by Django 5.0.14 on 2026-01-02 05:33

import correspondencia.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0033_firma_correspondencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcomunicacioninterna',
            name='evento',
            field=models.CharField(choices=[('CREADA', 'Comunicación Creada'), ('EDITADA', 'Comunicación Editada'), ('ENVIADA_APROBACION', 'Enviada a Aprobación'), ('APROBADA', 'Aprobada por Líder'), ('RECHAZADA', 'Rechazada por Líder'), ('FIRMA_SUBIDA', 'Firma Digital Subida'), ('DISTRIBUIDA', 'Distribuida a Destinatarios'), ('LEIDA', 'Leída por Usuario'), ('RESPUESTA_CREADA', 'Respuesta Creada'), ('ANULADA', 'Comunicación Anulada')], max_length=30),
        ),
        migrations.CreateModel(
            name='AnexoComunicacionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo anexo (PDF, Word o Excel)', max_length=300, upload_to=correspondencia.models.ruta_anexo_comunicacion_interna, validators=[correspondencia.models.validate_file_type_anexo, correspondencia.models.validate_file_size_anexo])),
                ('nombre_original', models.CharField(blank=True, help_text='Nombre original del archivo', max_length=255)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se subió el archivo')),
                ('comunicacion', models.ForeignKey(help_text='Comunicación interna a la que pertenece este anexo', on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='correspondencia.comunicacioninterna')),
                ('subido_por', models.ForeignKey(blank=True, help_text='Usuario que subió el anexo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_comunicacion_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo de Comunicación Interna',
                'verbose_name_plural': 'Anexos de Comunicaciones Internas',
                'ordering': ['fecha_carga'],
                'indexes': [models.Index(fields=['comunicacion', 'fecha_carga'], name='corresponde_comunic_9c756c_idx')],
            },
        ),
    ]
