# Generated by Django 5.0.14 on 2026-01-08 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0034_add_anexo_comunicacion_interna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificacion',
            name='corresponde_usuario_6858e9_idx',
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida', 'fecha_creacion'], name='corresponde_usuario_76aa45_idx'),
        ),
    ]
