# Generated by Django 5.0.14 on 2026-01-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0035_remove_notificacion_corresponde_usuario_6858e9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoentrante',
            name='fecha_recibida_gmail',
            field=models.DateTimeField(blank=True, help_text='Fecha INTERNALDATE registrada por Gmail/IMAP (recepción en servidor)', null=True),
        ),
    ]
