# Generated by Django 5.0.14 on 2026-01-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0036_correoentrante_fecha_recibida_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='codigo_trd',
            field=models.CharField(blank=True, db_index=True, help_text='Código TRD completo: oficina.serie.subserie (ej: 300.25.05)', max_length=255, null=True),
        ),
    ]
