# Generated by Django 5.0.14 on 2026-01-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0037_add_codigo_trd_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondencia',
            name='codigo_trd',
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='dias_personalizados',
            field=models.IntegerField(blank=True, help_text='Días de respuesta personalizados (1-15). Si se especifica, tiene prioridad sobre tiempo_respuesta y TRD.', null=True),
        ),
    ]
