# Generated by Django 5.0.14 on 2026-01-21 06:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0038_add_dias_personalizados'),
        ('documentos', '0019_agregar_relacion_series_oficinas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='tiempo_respuesta',
            field=models.CharField(blank=True, choices=[('1_DIA', '1 día hábil'), ('2_DIAS', '2 días hábiles'), ('MUY_URGENTE', 'Muy Urgente (3 días hábiles)'), ('URGENTE', 'Urgente (5 días hábiles)'), ('NORMAL', 'Normal (15 días hábiles)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('asignacion', 'Nueva Asignación'), ('compartido', 'Correspondencia Compartida'), ('respuesta', 'Nueva Respuesta'), ('vencimiento', 'Próximo a Vencer'), ('acceso_oficina', 'Acceso para otra oficina'), ('comunicacion_interna', 'Comunicación Interna'), ('aprobacion_pendiente', 'Aprobación Pendiente'), ('urgencia', 'Urgencia'), ('otro', 'Otro')], default='asignacion', max_length=25),
        ),
        migrations.CreateModel(
            name='CorrespondenciaUrgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_radicado', models.PositiveIntegerField(db_index=True, editable=False, help_text='Número secuencial compartido con Correspondencia normal', unique=True)),
                ('radicado', models.CharField(editable=False, help_text='Formato: URGENCIA-YYYY-NNNNN', max_length=50, unique=True)),
                ('fecha_radicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('horas_limite', models.PositiveSmallIntegerField(default=24, help_text='Horas laborales (8am-5pm, Lun-Vie) para responder')),
                ('fecha_limite', models.DateTimeField(help_text='Fecha límite calculada automáticamente')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESPONDIDA', 'Respondida'), ('VENCIDA', 'Vencida')], db_index=True, default='PENDIENTE', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('CRITICA', 'Crítica')], db_index=True, default='ALTA', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('motivo_urgencia', models.TextField(help_text='Justificación de por qué es urgente')),
                ('horas_transcurridas', models.DecimalField(decimal_places=2, default=0, help_text='Horas laborales transcurridas desde radicación', max_digits=6)),
                ('correo_entrante', models.ForeignKey(help_text='Correo entrante que origina esta urgencia', on_delete=django.db.models.deletion.CASCADE, related_name='urgencias_radicadas', to='correspondencia.correoentrante')),
                ('oficina_destino', models.ForeignKey(help_text='Toda la oficina recibe la urgencia, sin distribución', on_delete=django.db.models.deletion.PROTECT, related_name='urgencias_recibidas', to='documentos.oficinaproductora')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urgencias', to='documentos.seriedocumental')),
                ('subserie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='urgencias', to='documentos.subseriedocumental')),
                ('usuario_asignado', models.ForeignKey(blank=True, help_text='Usuario que tomó la urgencia para trabajarla', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgencias_asignadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_radica', models.ForeignKey(help_text='Usuario de ventanilla que radica la urgencia', on_delete=django.db.models.deletion.PROTECT, related_name='urgencias_radicadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_responde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='urgencias_respondidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correspondencia Urgente',
                'verbose_name_plural': 'Correspondencias Urgentes',
                'db_table': 'correspondencia_urgencia',
                'ordering': ['-fecha_radicacion'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoUrgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='urgencias/respuestas/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('tamaño_bytes', models.PositiveIntegerField(default=0)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('urgencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_respuesta', to='correspondencia.correspondenciaurgencia')),
            ],
            options={
                'verbose_name': 'Adjunto Urgencia',
                'verbose_name_plural': 'Adjuntos Urgencias',
                'db_table': 'adjuntos_urgencia',
            },
        ),
        migrations.AddIndex(
            model_name='correspondenciaurgencia',
            index=models.Index(fields=['estado', 'oficina_destino'], name='corresponde_estado_c0876b_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondenciaurgencia',
            index=models.Index(fields=['prioridad', 'estado'], name='corresponde_priorid_8f1520_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondenciaurgencia',
            index=models.Index(fields=['fecha_limite'], name='corresponde_fecha_l_be28f7_idx'),
        ),
    ]
