# Generated by Django 5.0.14 on 2026-01-21 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0039_alter_correspondencia_tiempo_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciasalida',
            name='respuesta_a_urgencia',
            field=models.ForeignKey(blank=True, help_text='Urgencia a la que responde este documento (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_salientes', to='correspondencia.correspondenciaurgencia'),
        ),
        migrations.AlterField(
            model_name='correspondenciaurgencia',
            name='numero_radicado',
            field=models.PositiveIntegerField(db_index=True, editable=False, help_text='Número secuencial compartido con correspondencia ENTRANTE', unique=True),
        ),
        migrations.AlterField(
            model_name='correspondenciaurgencia',
            name='radicado',
            field=models.CharField(editable=False, help_text='Formato: ENTRANTE-YYYY-NNNNN compartido con Correspondencia', max_length=50, unique=True),
        ),
    ]
