# Generated by Django 5.0.14 on 2026-01-22 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0040_add_respuesta_a_urgencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoentrante',
            name='urgencia_asociada',
            field=models.ForeignKey(blank=True, help_text='Urgencia creada a partir de este correo (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correo_origen', to='correspondencia.correspondenciaurgencia'),
        ),
    ]
