# Generated by Django 5.0.14 on 2026-01-30 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0041_add_urgencia_asociada_to_correoentrante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='correoentrante',
            name='en_papelera',
            field=models.BooleanField(db_index=True, default=False, help_text='En papelera: no se muestra en bandeja activa; se conserva para registro.'),
        ),
        migrations.AddField(
            model_name='correoentrante',
            name='fecha_papelera',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se envió a papelera.', null=True),
        ),
        migrations.AddField(
            model_name='correoentrante',
            name='motivo_papelera',
            field=models.CharField(blank=True, choices=[('NO_APLICABLE', 'No aplicable (no es correspondencia institucional)'), ('NOTIFICACION_AUTOMATICA', 'Notificación automática (recibidos, avisos de sistema)'), ('INVITACION_PROMOCIONAL', 'Invitación o promocional'), ('SPAM', 'Spam o correo no deseado'), ('OTRO', 'Otro')], help_text='Motivo por el cual se envió a papelera.', max_length=32),
        ),
        migrations.AddField(
            model_name='correoentrante',
            name='usuario_papelera',
            field=models.ForeignKey(blank=True, help_text='Usuario que envió el correo a papelera.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_enviados_papelera', to=settings.AUTH_USER_MODEL),
        ),
    ]
