# Generated by Django 5.0.14 on 2026-01-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0042_correo_entrante_papelera'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSincronizacionCorreos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(default='GMAIL_IMAP', help_text='Origen de la sincronización (ej: GMAIL_IMAP).', max_length=32)),
                ('ultimo_inicio', models.DateTimeField(blank=True, null=True)),
                ('ultimo_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('RUNNING', 'En ejecución'), ('SUCCESS', 'Exitosa'), ('FAIL', 'Fallida')], default='SUCCESS', max_length=16)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Sincronización de Correos',
                'verbose_name_plural': 'Estado de Sincronización de Correos',
            },
        ),
    ]
