# Generated by Django - Permitir destinatario nullable para radicación rápida

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0043_estado_sincronizacion_correos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='destinatario_contacto',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text='Contacto externo al que se dirige la respuesta (automático o seleccionado).',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='correspondencia_recibida_saliente',
                to='correspondencia.contacto',
            ),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='destinatario_email',
            field=models.EmailField(
                blank=True,
                default='',
                editable=False,
                help_text='Email del destinatario al momento de la aprobación (automático).',
                max_length=254,
            ),
        ),
    ]
