# Generated by Django 5.0.14 on 2026-02-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0044_correspondenciasalida_destinatario_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='anexos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='clasificacion_comunicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='direccion_correo_remitente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='empresa_transportadora',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='entidad_persona_remitente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='estado_respuesta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='fecha_limite_respuesta_manual',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='fecha_notificacion_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='fecha_primer_seguimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='fecha_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='fecha_segundo_seguimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='funcionario_responsable_tramite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='medio_recibido',
            field=models.CharField(blank=True, choices=[('', '---------'), ('EMAIL', 'Email'), ('CORREO_CERTIFICADO', 'Correo certificado'), ('PERSONAL', 'Personal')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='numero_folios',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='radicado_enviado_respuesta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
