# Generated by Django 5.0.14 on 2026-02-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0045_campos_temporales_radicacion_rapida'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='origen_radicacion',
            field=models.CharField(choices=[('NORMAL', 'Radicación Normal'), ('RAPIDA', 'Radicación Rápida'), ('CORREO', 'Desde Correo Electrónico')], db_index=True, default='NORMAL', help_text='Indica cómo fue radicada esta correspondencia', max_length=20),
        ),
    ]
