# Generated by Django 5.0.14 on 2026-02-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0048_add_tipo_tramite_radicacion_rapida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicacioninterna',
            name='comunicacion_origen',
            field=models.ForeignKey(blank=True, help_text='Comunicación original a la que responde (múltiples respuestas permitidas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='correspondencia.comunicacioninterna'),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='estado_respuesta',
            field=models.CharField(blank=True, choices=[('', '---------'), ('PENDIENTE', 'Pendiente'), ('RESPONDIDA', 'Respondida'), ('VENCIDA', 'Vencida')], help_text='Solo para radicación rápida: Pendiente, Respondida o Vencida.', max_length=20, null=True),
        ),
    ]
