# Generated by Django 5.0.14 on 2026-02-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0049_estado_respuesta_rapida_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='tipo_tramite',
            field=models.CharField(blank=True, choices=[('', '---------'), ('PT', 'Petición (PT)'), ('PTA', 'Petición Anticipada (PTA)'), ('DM', 'Documento Médico (DM)'), ('HC', 'Historia Clínica (HC)'), ('CMC', 'Cita Médica/Consulta (CMC)'), ('PQRSF', 'PQRSF'), ('GLA', 'Queja/Reclamo (GLA)'), ('SD', 'Solicitud de Documentos (SD)'), ('AT', 'Asunto Técnico (AT)'), ('NA', 'No Aplica (NA)')], help_text='Tipo de trámite (radicación rápida)', max_length=50, null=True),
        ),
    ]
