# Generated by Django 5.0.14 on 2026-02-10 01:36

from django.db import migrations, models


def crear_tipos_tramite_iniciales(apps, schema_editor):
    """
    Crea los tipos de trámite iniciales con sus días de respuesta.
    """
    TipoTramite = apps.get_model('correspondencia', 'TipoTramite')
    
    tipos_iniciales = [
        {
            'codigo': 'PT',
            'nombre': 'Petición',
            'descripcion': 'Petición general de información o solicitud de servicios',
            'dias_respuesta': 15,
            'orden': 10
        },
        {
            'codigo': 'PTA',
            'nombre': 'Petición Anticipada',
            'descripcion': 'Petición que requiere respuesta prioritaria en corto plazo',
            'dias_respuesta': 4,
            'orden': 20
        },
        {
            'codigo': 'DM',
            'nombre': 'Documento Médico',
            'descripcion': 'Solicitud relacionada con documentos médicos',
            'dias_respuesta': 5,
            'orden': 30
        },
        {
            'codigo': 'HC',
            'nombre': 'Historia Clínica',
            'descripcion': 'Solicitud de historia clínica o documentos asociados',
            'dias_respuesta': 3,
            'orden': 40
        },
        {
            'codigo': 'CMC',
            'nombre': 'Cita Médica/Consulta',
            'descripcion': 'Solicitud de asignación o reprogramación de cita médica',
            'dias_respuesta': 2,
            'orden': 50
        },
        {
            'codigo': 'PQRSF',
            'nombre': 'PQRSF',
            'descripcion': 'Peticiones, Quejas, Reclamos, Sugerencias o Felicitaciones',
            'dias_respuesta': 15,
            'orden': 60
        },
        {
            'codigo': 'GLA',
            'nombre': 'Queja/Reclamo',
            'descripcion': 'Queja o reclamo sobre el servicio prestado',
            'dias_respuesta': 15,
            'orden': 70
        },
        {
            'codigo': 'SD',
            'nombre': 'Solicitud de Documentos',
            'descripcion': 'Solicitud de documentos generales o copias',
            'dias_respuesta': 10,
            'orden': 80
        },
        {
            'codigo': 'AT',
            'nombre': 'Asunto Técnico',
            'descripcion': 'Consulta o trámite de naturaleza técnica',
            'dias_respuesta': 8,
            'orden': 90
        },
        {
            'codigo': 'NA',
            'nombre': 'No Aplica',
            'descripcion': 'Correspondencia sin plazo de respuesta definido',
            'dias_respuesta': None,
            'orden': 100
        },
    ]
    
    for tipo_data in tipos_iniciales:
        TipoTramite.objects.create(
            codigo=tipo_data['codigo'],
            nombre=tipo_data['nombre'],
            descripcion=tipo_data['descripcion'],
            dias_respuesta=tipo_data['dias_respuesta'],
            activo=True,
            orden=tipo_data['orden']
        )


def revertir_tipos_tramite(apps, schema_editor):
    """
    Elimina los tipos de trámite creados (para rollback).
    """
    TipoTramite = apps.get_model('correspondencia', 'TipoTramite')
    TipoTramite.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0050_alter_correspondencia_tipo_tramite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del tipo de trámite (ej: PT, PTA, PQRSF)', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tipo de trámite', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de trámite (opcional)', verbose_name='Descripción')),
                ('dias_respuesta', models.PositiveIntegerField(blank=True, help_text='Número de días hábiles para responder. Dejar vacío si no aplica plazo.', null=True, verbose_name='Días Hábiles de Respuesta')),
                ('activo', models.BooleanField(default=True, help_text='Solo los tipos activos aparecen en los formularios', verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en los formularios (menor número = primera posición)', verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Tipo de Trámite',
                'verbose_name_plural': 'Tipos de Trámite',
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.RunPython(crear_tipos_tramite_iniciales, revertir_tipos_tramite),
    ]
