# Generated by Django 5.0.14 on 2026-02-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0051_crear_modelo_tipo_tramite'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='fecha_recepcion_documento',
            field=models.DateField(blank=True, help_text='Fecha en que se recibió físicamente el documento (importante para calcular plazo de respuesta)', null=True),
        ),
    ]
