# Generated by Django 5.0.14 on 2026-02-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0052_correspondencia_fecha_recepcion_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='email_funcionario_responsable',
            field=models.EmailField(blank=True, help_text='Correo electrónico del funcionario responsable del trámite', max_length=254, null=True),
        ),
    ]
