# Generated by Django 5.0.14 on 2026-02-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0053_add_email_funcionario_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciasalida',
            name='evidencia_respuesta',
            field=models.FileField(blank=True, help_text='Adjunte evidencia de que la correspondencia fue respondida (PDF, imagen, etc.).', null=True, upload_to='correspondencia/salida_evidencias/'),
        ),
        migrations.AddField(
            model_name='correspondenciasalida',
            name='fue_respondida',
            field=models.BooleanField(default=False, help_text='Marcar cuando el funcionario haya respondido esta correspondencia.'),
        ),
        migrations.AlterField(
            model_name='historialcorrespondencia',
            name='evento',
            field=models.CharField(choices=[('RADICADA', 'Radicada'), ('ASIGNADA_USUARIO', 'Asignada a Usuario'), ('LEIDA', 'Leída por Oficina'), ('RESPONDIDA', 'Respondida'), ('SELLO_IMPRESO', 'Sello impreso'), ('REDISTRIBUIDA_INTERNA', 'Redistribuida internamente'), ('COMPARTIDA_OFICINA', 'Compartida con oficina'), ('NOTIFICACION', 'Notificación enviada'), ('ERROR', 'Error')], max_length=30),
        ),
    ]
