# Generated by Django 5.0.14 on 2026-02-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0054_correspondenciasalida_evidencia_respuesta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondenciasalida',
            name='evidencia_respuesta',
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='fue_respondida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historialcorrespondencia',
            name='evento',
            field=models.CharField(choices=[('RADICADA', 'Radicada'), ('ASIGNADA_USUARIO', 'Asignada a Usuario'), ('LEIDA', 'Leída por Oficina'), ('RESPONDIDA', 'Respondida'), ('SELLO_IMPRESO', 'Sello impreso'), ('REDISTRIBUIDA_INTERNA', 'Redistribuida internamente'), ('COMPARTIDA_OFICINA', 'Compartida con oficina')], max_length=30),
        ),
    ]
