# Generated by Django 5.0.14 on 2026-02-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0055_add_fue_respondida_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciasalida',
            name='evidencia_respuesta',
            field=models.FileField(blank=True, null=True, upload_to='salidas/evidencias/%Y/%m/'),
        ),
    ]
