# Generated by Django 5.0.14 on 2026-02-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0056_add_evidencia_respuesta_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciasalida',
            name='funcionario_envia',
            field=models.CharField(blank=True, default='', help_text='Nombre del funcionario que envía la correspondencia.', max_length=255),
        ),
    ]
