# Generated by Django 5.0.14 on 2026-02-24 19:51

import correspondencia.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0057_add_funcionario_envia_to_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoCorrespondenciaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Escaneo o documento adjunto de la correspondencia', max_length=255, upload_to=correspondencia.models.ruta_adjunto_correspondencia_rapida)),
                ('nombre_original', models.CharField(blank=True, help_text='Nombre original del archivo', max_length=255)),
                ('tipo_mime', models.CharField(blank=True, help_text='Tipo MIME del archivo (ej: application/pdf, image/jpeg)', max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_rapidos', to='correspondencia.correspondencia')),
            ],
            options={
                'verbose_name': 'Adjunto de Correspondencia Rápida',
                'verbose_name_plural': 'Adjuntos de Correspondencia Rápida',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
