# Generated by Django 5.0.14 on 2026-02-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0058_adjuntocorrespondenciarapida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmacorrespondencia',
            name='nombre_firmante',
            field=models.CharField(blank=True, default='', help_text='Nombre del funcionario que firmó (snapshot, opcional)', max_length=255),
        ),
    ]
