# Generated by Django 5.0.14 on 2026-03-05 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0059_nombre_firmante_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('ELIMINACION', 'Eliminación')], default='EDICION', max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('campos_modificados', models.JSONField(blank=True, default=dict, help_text='Diccionario con campos modificados: {campo: {antes, despues}}')),
                ('contacto_nombre_snapshot', models.CharField(blank=True, help_text='Nombre del contacto al momento del cambio (para si se elimina)', max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('contacto', models.ForeignKey(blank=True, help_text='Contacto afectado por el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_cambios', to='correspondencia.contacto')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_contactos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Contacto',
                'verbose_name_plural': 'Auditorías de Contactos',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
