# Generated by Django 5.0.14 on 2026-03-10

import correspondencia.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0060_auditoria_contacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaAuxiliarCorrespondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_imagen', models.ImageField(help_text='Imagen de la firma auxiliar capturada', upload_to=correspondencia.models.ruta_firma_correspondencia)),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('nombre_firmante', models.CharField(help_text='Nombre del firmante auxiliar', max_length=255)),
                ('cargo_firmante', models.CharField(help_text='Cargo del firmante auxiliar', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas_auxiliares', to='correspondencia.correspondencia')),
                ('recolector', models.ForeignKey(help_text='Usuario que recolectó la firma auxiliar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_auxiliares_recolectadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firma Auxiliar de Correspondencia',
                'verbose_name_plural': 'Firmas Auxiliares de Correspondencia',
                'ordering': ['-fecha_firma'],
            },
        ),
    ]
