# Generated by Django 5.0.14 on 2026-03-21 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0065_comunicacioninterna_clasificacion_documental'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoProblematico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Message-ID único del correo problemático', max_length=255, unique=True)),
                ('remitente', models.EmailField(blank=True, max_length=254)),
                ('asunto', models.CharField(blank=True, max_length=500)),
                ('cuerpo_texto', models.TextField(blank=True, help_text='Cuerpo en texto plano para revisión operativa')),
                ('cuerpo_html', models.TextField(blank=True, help_text='Cuerpo HTML para revisión operativa')),
                ('fecha_recepcion_original', models.DateTimeField(blank=True, null=True)),
                ('fecha_recibida_gmail', models.DateTimeField(blank=True, null=True)),
                ('fecha_lectura_imap', models.DateTimeField(default=django.utils.timezone.now)),
                ('carpeta_origen', models.CharField(blank=True, default='', max_length=128)),
                ('flujo_origen', models.CharField(blank=True, default='', max_length=32)),
                ('motivo_problema', models.CharField(default='VALIDACION_ADJUNTO', max_length=64)),
                ('detalle_problema', models.TextField(blank=True, default='')),
                ('adjuntos_resumen', models.TextField(blank=True, default='[]')),
                ('resuelto', models.BooleanField(db_index=True, default=False)),
                ('fecha_resuelto', models.DateTimeField(blank=True, null=True)),
                ('correo_entrante_asociado', models.ForeignKey(blank=True, help_text='Correo entrante creado posteriormente cuando el incidente se resolvió.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemas_origen', to='correspondencia.correoentrante')),
            ],
            options={
                'verbose_name': 'Correo Problemático',
                'verbose_name_plural': 'Correos Problemáticos',
                'ordering': ['resuelto', '-fecha_recibida_gmail', '-fecha_lectura_imap'],
            },
        ),
    ]
