# Generated by Django 5.0.14 on 2026-03-25 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0066_correoproblematico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_relativa', models.CharField(max_length=500, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=64)),
                ('tipo_fuente', models.CharField(default='archivo', max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('indexado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento del asistente',
                'verbose_name_plural': 'Documentos del asistente',
                'db_table': 'asistente_documento',
                'ordering': ['ruta_relativa'],
            },
        ),
        migrations.CreateModel(
            name='AsistenteConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nueva conversación', max_length=160)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ARCHIVADA', 'Archivada')], default='ACTIVA', max_length=20)),
                ('ultima_pregunta_at', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistente_conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación del asistente',
                'verbose_name_plural': 'Conversaciones del asistente',
                'db_table': 'asistente_conversacion',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='AsistenteMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], max_length=20)),
                ('contenido', models.TextField()),
                ('citas', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='correspondencia.asistenteconversacion')),
            ],
            options={
                'verbose_name': 'Mensaje del asistente',
                'verbose_name_plural': 'Mensajes del asistente',
                'db_table': 'asistente_mensaje',
                'ordering': ['creado_en', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AsistenteChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('contenido', models.TextField()),
                ('search_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='correspondencia.asistentedocumento')),
            ],
            options={
                'verbose_name': 'Chunk del asistente',
                'verbose_name_plural': 'Chunks del asistente',
                'db_table': 'asistente_chunk',
                'ordering': ['documento_id', 'orden'],
                'unique_together': {('documento', 'orden')},
            },
        ),
    ]
