# Generated by Django 5.0.14 on 2026-03-27 17:06

import django.db.models.deletion
from django.db import migrations, models


def _normalizar_dominio(valor):
    if not valor:
        return ''
    dominio = str(valor).strip().lower()
    if '@' in dominio:
        dominio = dominio.split('@')[-1]
    return dominio.strip(' .')


def poblar_dominios_principales(apps, schema_editor):
    EntidadExterna = apps.get_model('correspondencia', 'EntidadExterna')
    EntidadExternaDominio = apps.get_model('correspondencia', 'EntidadExternaDominio')

    for entidad in EntidadExterna.objects.exclude(dominio__isnull=True).exclude(dominio=''):
        dominio = _normalizar_dominio(entidad.dominio)
        if not dominio:
            continue

        EntidadExternaDominio.objects.get_or_create(
            dominio=dominio,
            defaults={
                'entidad_externa_id': entidad.id,
                'activo': True,
            }
        )


def revertir_dominios_principales(apps, schema_editor):
    EntidadExternaDominio = apps.get_model('correspondencia', 'EntidadExternaDominio')
    EntidadExternaDominio.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0067_asistentedocumento_asistenteconversacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadExternaDominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=120, unique=True, verbose_name='Dominio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entidad_externa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios_secundarios', to='correspondencia.entidadexterna', verbose_name='Entidad Externa')),
            ],
            options={
                'verbose_name': 'Dominio autorizado de entidad',
                'verbose_name_plural': 'Dominios autorizados de entidades',
                'ordering': ['dominio'],
            },
        ),
        migrations.RunPython(poblar_dominios_principales, revertir_dominios_principales),
    ]
