# Generated by Django 5.0.14 on 2026-03-28 20:31

import correspondencia.chat_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0069_chat_soporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to=correspondencia.chat_models.chat_adjunto_path)),
                ('nombre_original', models.CharField(max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='correspondencia.chatmessage')),
            ],
            options={
                'verbose_name': 'Adjunto de chat',
                'verbose_name_plural': 'Adjuntos de chat',
            },
        ),
    ]
