# Generated by Django 5.0.14 on 2026-04-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0071_respuesta_discrecional_permiso_y_trazabilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialsalida',
            name='tipo_evento',
            field=models.CharField(choices=[('CREACION', 'Creación Borrador'), ('RESPUESTA_DISCRECIONAL', 'Respuesta Discrecional'), ('MODIFICACION', 'Modificación Borrador'), ('ENVIO_APROBACION', 'Enviado a Aprobación'), ('APROBACION', 'Aprobado por Ventanilla'), ('RECHAZO', 'Rechazado por Ventanilla'), ('INTENTO_ENVIO', 'Intento de Envío Email'), ('ENVIO_EXITOSO', 'Email Enviado Exitosamente'), ('ENVIO_FALLIDO', 'Error al Enviar Email')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('asignacion', 'Nueva Asignación'), ('compartido', 'Correspondencia Compartida'), ('respuesta', 'Nueva Respuesta'), ('vencimiento', 'Próximo a Vencer'), ('acceso_oficina', 'Acceso para otra oficina'), ('comunicacion_interna', 'Comunicación Interna'), ('aprobacion_pendiente', 'Aprobación Pendiente'), ('urgencia', 'Urgencia'), ('rebote', 'Rebote de Envío'), ('otro', 'Otro')], default='asignacion', max_length=25),
        ),
    ]
