# Generated by Django 5.0.14 on 2026-05-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0073_correoproblematico_respaldo_eml'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostmarkWebhookEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=32)),
                ('postmark_message_id', models.CharField(db_index=True, max_length=64)),
                ('recipient', models.EmailField(blank=True, default='', max_length=254)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('recibido_at', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('resultado', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Evento webhook Postmark',
                'verbose_name_plural': 'Eventos webhook Postmark',
                'ordering': ['-recibido_at'],
            },
        ),
        migrations.AddField(
            model_name='comunicaciondestinatario',
            name='postmark_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='MessageID UUID devuelto por Postmark al enviar.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciasalida',
            name='postmark_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='MessageID UUID devuelto por Postmark al enviar.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='salidadestinatario',
            name='postmark_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='MessageID UUID devuelto por Postmark al enviar.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historialsalida',
            name='tipo_evento',
            field=models.CharField(choices=[('CREACION', 'Creación Borrador'), ('RESPUESTA_DISCRECIONAL', 'Respuesta Discrecional'), ('MODIFICACION', 'Modificación Borrador'), ('ENVIO_APROBACION', 'Enviado a Aprobación'), ('APROBACION', 'Aprobado por Ventanilla'), ('RECHAZO', 'Rechazado por Ventanilla'), ('INTENTO_ENVIO', 'Intento de Envío Email'), ('ENVIO_EXITOSO', 'Email Enviado Exitosamente'), ('ENVIO_FALLIDO', 'Error al Enviar Email'), ('ENTREGA_CONFIRMADA', 'Entrega Confirmada por Postmark')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='postmarkwebhookevento',
            constraint=models.UniqueConstraint(fields=('record_type', 'postmark_message_id', 'recipient'), name='uniq_postmark_webhook_evento'),
        ),
    ]
