# Generated by Django 5.0.14 on 2025-04-07 22:34

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadProductora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaPaciente',
            fields=[
                ('consecutivo', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('num_identificacion', models.IntegerField(unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('primer_nombre_padre', models.CharField(blank=True, max_length=50, null=True)),
                ('segundo_nombre_padre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido_padre', models.CharField(blank=True, max_length=50, null=True)),
                ('segundo_apellido_padre', models.CharField(blank=True, max_length=50, null=True)),
                ('Numero_historia_clinica', models.IntegerField(unique=True)),
                ('caja', models.CharField(max_length=20)),
                ('carpeta', models.CharField(max_length=20)),
                ('gabeta', models.IntegerField(blank=True, null=True)),
                ('tipo_identificacion', models.CharField(default='Cedula de Ciudadania', max_length=20)),
                ('sexo', models.CharField(default='Masculino', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OficinaProductora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SerieDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.oficinaproductora')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDeArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado_archivo', models.BooleanField(default=True)),
                ('numero_orden', models.IntegerField(default=0)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_documental', models.CharField(max_length=255)),
                ('fecha_archivo', models.DateField(blank=True, null=True)),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('soporte_fisico', models.BooleanField(default=False)),
                ('soporte_electronico', models.BooleanField(default=False)),
                ('caja', models.IntegerField(blank=True, null=True)),
                ('carpeta', models.IntegerField(blank=True, null=True)),
                ('tomo_legajo_libro', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_folios', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=255, null=True)),
                ('cantidad_documentos_electronicos', models.IntegerField(blank=True, null=True)),
                ('tamano_documentos_electronicos', models.CharField(blank=True, max_length=50, null=True)),
                ('identificador_documento', models.IntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('codigo_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='documentos.seriedocumental')),
            ],
            options={
                'permissions': [('view_own_registro', 'Puede ver sus propios registros'), ('edit_own_registro', 'Puede editar sus propios registros'), ('delete_own_registro', 'Puede eliminar sus propios registros')],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=300, upload_to=documentos.models.documento_upload_path, validators=[documentos.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documentos.registrodearchivo')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoUsuarioSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso_crear', models.BooleanField(default=False)),
                ('permiso_editar', models.BooleanField(default=False)),
                ('permiso_consultar', models.BooleanField(default=True)),
                ('permiso_eliminar', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.seriedocumental')),
            ],
        ),
        migrations.CreateModel(
            name='SubserieDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.seriedocumental')),
            ],
        ),
        migrations.AddField(
            model_name='registrodearchivo',
            name='codigo_subserie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='documentos.subseriedocumental'),
        ),
        migrations.CreateModel(
            name='UnidadAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('entidad_productora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='documentos.entidadproductora')),
            ],
        ),
        migrations.AddField(
            model_name='oficinaproductora',
            name='unidad_administrativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficinas', to='documentos.unidadadministrativa'),
        ),
        migrations.CreateModel(
            name='FUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('elaborado_por_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('elaborado_por_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('elaborado_por_lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('elaborado_por_fecha', models.DateField(blank=True, null=True)),
                ('entregado_por_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('entregado_por_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('entregado_por_lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('entregado_por_fecha', models.DateField(blank=True, null=True)),
                ('recibido_por_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('recibido_por_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('recibido_por_lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('recibido_por_fecha', models.DateField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuids', to=settings.AUTH_USER_MODEL)),
                ('entidad_productora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.entidadproductora')),
                ('objeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.objeto')),
                ('oficina_productora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.oficinaproductora')),
                ('registros', models.ManyToManyField(blank=True, related_name='fuids', to='documentos.registrodearchivo')),
                ('unidad_administrativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.unidadadministrativa')),
            ],
            options={
                'permissions': [('view_own_fuid', 'Puede ver sus propios FUIDs'), ('edit_own_fuid', 'Puede editar sus propios FUIDs'), ('delete_own_fuid', 'Puede eliminar sus propios FUIDs')],
            },
        ),
    ]
