# Generated by Django 5.0.14 on 2025-04-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo del usuario (opcional)', max_length=150, null=True),
        ),
    ]
