# Generated by Django 5.0.14 on 2025-10-05 05:55

import django.db.models.deletion
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_perfilusuario_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Nacionalidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='Fecha_de_visita_de_la_tarjeta',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='año_de_registro',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='estado_de_migracion',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='num_identificacion_secundario',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='ultimo_registro_de_visita_en_la_base_de_datos',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fuid',
            name='notas',
            field=models.CharField(blank=True, max_length=245, null=True),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='Numero_historia_clinica',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='caja',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='carpeta',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='gabeta',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='num_identificacion',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='primer_apellido',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='primer_apellido_padre',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='primer_nombre',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='primer_nombre_padre',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='segundo_apellido',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='segundo_apellido_padre',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='segundo_nombre',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='segundo_nombre_padre',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='sexo',
            field=models.CharField(db_index=True, default='Masculino', max_length=10),
        ),
        migrations.AlterField(
            model_name='registrodearchivo',
            name='identificador_documento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='registrodearchivo',
            name='notas',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, default=documentos.models.nacionalidad_colombiana_default, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.nacionalidad'),
        ),
        migrations.AddField(
            model_name='fichapaciente',
            name='tipo_identificacion_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segundario', to='documentos.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='tipo_identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.tipodocumento'),
        ),
        migrations.AddConstraint(
            model_name='fichapaciente',
            constraint=models.UniqueConstraint(fields=('num_identificacion', 'tipo_identificacion'), name='unique_identificacion_tipo'),
        ),
    ]
