# Generated by Django 5.2.1 on 2025-11-23 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_nacionalidad_tipodocumento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproceso_solicitante', models.CharField(blank=True, help_text='Subproceso que solicita', max_length=255, null=True)),
                ('codigo_trd', models.CharField(blank=True, help_text='Código TRD', max_length=50, null=True)),
                ('descripcion_documento', models.TextField(blank=True, help_text='Descripción del documento (serie/subserie y fecha)', null=True)),
                ('tipo_prestamo', models.CharField(choices=[('FISICO', 'Físico'), ('VIRTUAL', 'Virtual')], max_length=10)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En Proceso'), ('ENTREGADO', 'Entregado'), ('PRESTAMO_ACTIVO', 'Préstamo Activo'), ('DEVUELTO', 'Devuelto'), ('RECHAZADO', 'Rechazado'), ('RECHAZADO_USUARIO', 'Rechazado por Usuario'), ('VENCIDO', 'Vencido')], default='SOLICITADO', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Solo para préstamos físicos (5 días hábiles)', null=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('vobo_jefe_nombre', models.CharField(blank=True, default='Eliana Gelves', help_text='Nombre del jefe que aprueba', max_length=255, null=True)),
                ('vobo_jefe_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('vobo_jefe_fecha', models.DateField(blank=True, null=True)),
                ('documento_escaneado', models.FileField(blank=True, help_text='PDF escaneado del documento', null=True, upload_to='prestamos/escaneados/')),
                ('documento_virtual', models.FileField(blank=True, help_text='PDF generado para préstamo virtual', null=True, upload_to='prestamos/virtuales/')),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('motivo_rechazo_usuario', models.TextField(blank=True, help_text='Motivo si el usuario rechaza el documento', null=True)),
                ('documento_devuelto', models.BooleanField(default=False)),
                ('documento_danado', models.BooleanField(default=False)),
                ('observaciones_dano', models.TextField(blank=True, help_text='Observaciones sobre daños o faltantes', null=True)),
                ('confirmado_por_usuario', models.BooleanField(default=False, help_text='Usuario confirma que recibió el documento correcto')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('fuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='documentos.fuid')),
                ('oficina_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_oficina', to='documentos.oficinaproductora')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_procesados', to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='documentos.registrodearchivo')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.seriedocumental')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('subserie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.subseriedocumental')),
            ],
            options={
                'verbose_name': 'Préstamo Documental',
                'verbose_name_plural': 'Préstamos Documentales',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(help_text='Tipo de evento: estado cambiado, documento subido, etc.', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='documentos.prestamodocumental')),
            ],
            options={
                'verbose_name': 'Historial de Préstamo',
                'verbose_name_plural': 'Historiales de Préstamos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='prestamodocumental',
            index=models.Index(fields=['estado', '-fecha_solicitud'], name='documentos__estado_3ea9a3_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamodocumental',
            index=models.Index(fields=['solicitante', '-fecha_solicitud'], name='documentos__solicit_09cbd2_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamodocumental',
            index=models.Index(fields=['tipo_prestamo', 'estado'], name='documentos__tipo_pr_9c1537_idx'),
        ),
    ]
