# Generated by Django 5.2.1 on 2025-11-24 04:56

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_prestamodocumental_historialprestamo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEscaneadoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Documento escaneado (PDF, Word o Excel)', max_length=300, upload_to=documentos.models.documento_escaneado_prestamo_upload_path, validators=[documentos.models.validate_file_type_prestamo, documentos.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo_original', models.CharField(blank=True, help_text='Nombre original del archivo', max_length=255, null=True)),
                ('confirmado', models.BooleanField(default=False, help_text='Confirmado que el archivo se subió correctamente')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_escaneados', to='documentos.prestamodocumental')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_escaneados_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Escaneado de Préstamo',
                'verbose_name_plural': 'Documentos Escaneados de Préstamos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
