# Generated by Django 5.2.1 on 2025-11-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_add_documento_escaneado_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamodocumental',
            name='documento_rechazo',
            field=models.FileField(blank=True, help_text='Documento adjunto explicando los motivos del rechazo', null=True, upload_to='prestamos/rechazos/'),
        ),
    ]
