# Generated by Django 5.2.1 on 2025-11-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_add_documento_rechazo_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamodocumental',
            name='fecha_reintegracion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que Archivo Central reintegró el documento a su ubicación física', null=True),
        ),
        migrations.AlterField(
            model_name='prestamodocumental',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el usuario devolvió el documento', null=True),
        ),
    ]
