# Generated by Django 5.2.1 on 2025-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_add_fecha_reintegracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamodocumental',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En Proceso'), ('ENTREGADO', 'Entregado'), ('PRESTAMO_ACTIVO', 'Préstamo Activo'), ('DEVUELTO', 'Devuelto'), ('REINTEGRADO', 'Reintegrado'), ('RECHAZADO', 'Rechazado'), ('RECHAZADO_USUARIO', 'Rechazado por Usuario'), ('VENCIDO', 'Vencido')], default='SOLICITADO', max_length=20),
        ),
    ]
