# Generated by Django 5.2.1 on 2025-11-26 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_add_estado_reintegrado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamodocumental',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Solo para préstamos físicos (10 días hábiles para Historia Clínica, 20 días hábiles para otros)', null=True),
        ),
        migrations.CreateModel(
            name='NotificacionAvisoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_oficio', models.FileField(help_text='Documento oficio de notificación', upload_to='prestamos/notificaciones/')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True)),
                ('notificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('oficina_notificada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.oficinaproductora')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_aviso', to='documentos.prestamodocumental')),
            ],
            options={
                'verbose_name': 'Notificación de Aviso',
                'verbose_name_plural': 'Notificaciones de Aviso',
                'ordering': ['-fecha_notificacion'],
            },
        ),
    ]
