# Generated by Django 5.0.14 on 2025-12-21 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_add_notificacion_aviso_prestamo'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='oficinaproductora',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código de la oficina (opcional)', max_length=50, null=True),
        ),
        
    ]
