# Generated by Django 5.0.14 on 2025-12-21 23:25

import django.db.models.deletion
from django.db import migrations, models


def _create_default_proceso(apps, schema_editor):
    MacroProceso = apps.get_model('documentos', 'MacroProceso')
    Proceso = apps.get_model('documentos', 'Proceso')
    mp, _ = MacroProceso.objects.get_or_create(numero=1, defaults={'nombre': 'Por defecto'})
    if not Proceso.objects.filter(id=1).exists():
        Proceso.objects.create(id=1, numero=1, nombre='Por defecto', sigla='DEF', macroproceso=mp)


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_macroproceso_oficinaproductora_codigo_proceso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número secuencial del macroproceso', unique=True)),
                ('nombre', models.CharField(help_text='Nombre del macroproceso (ej: ESTRATÉGICOS, MISIONALES)', max_length=255)),
            ],
            options={
                'verbose_name': 'Macroproceso',
                'verbose_name_plural': 'Macroprocesos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número del proceso')),
                ('nombre', models.CharField(help_text='Nombre del proceso', max_length=255)),
                ('sigla', models.CharField(help_text='Sigla del proceso (ej: DIR, THS, SIG)', max_length=20)),
                ('macroproceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='documentos.macroproceso')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['macroproceso__numero', 'numero'],
                'unique_together': {('numero', 'macroproceso')},
            },
        ),
        migrations.RunPython(
            _create_default_proceso,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='oficinaproductora',
            name='proceso',
            field=models.ForeignKey(default=1, help_text='Proceso al que pertenece esta oficina (Subproceso)', on_delete=django.db.models.deletion.PROTECT, related_name='oficinas', to='documentos.proceso'),
            preserve_default=False,
        ),
    ]
