# Generated by Django 5.2.1 on 2025-12-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0011_macroproceso_proceso_oficinaproductora_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_firma_creada',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se creó la firma', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='firma_digital',
            field=models.ImageField(blank=True, help_text='Firma manuscrita del usuario para usar en documentos', null=True, upload_to='firmas/'),
        ),
    ]
