# Generated by Django 5.2.1 on 2025-12-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0012_perfilusuario_fecha_firma_creada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección de residencia', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, help_text='Fecha de registro del usuario', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número de documento de identidad', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='solicita_lider',
            field=models.BooleanField(default=False, help_text='El usuario solicita ser líder de oficina'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte'), ('RC', 'Registro Civil'), ('NIT', 'NIT'), ('PEP', 'Permiso Especial de Permanencia'), ('PPT', 'Permiso por Protección Temporal')], default='CC', help_text='Tipo de documento de identidad', max_length=3),
        ),
    ]
