# Generated by Django 5.2.1 on 2025-12-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0013_alter_perfilusuario_options_perfilusuario_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficinaproductora',
            name='codigo_trd',
            field=models.CharField(blank=True, help_text='Código TRD de la oficina', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seriedocumental',
            name='codigo_trd',
            field=models.CharField(blank=True, help_text='Código TRD de la serie', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subseriedocumental',
            name='codigo_trd',
            field=models.CharField(blank=True, help_text='Código TRD de la subserie', max_length=255, null=True, unique=True),
        ),
    ]
