# Generated by Django 5.0.14 on 2026-01-08 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0014_oficinaproductora_codigo_trd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.oficinaproductora'),
        ),
    ]
