# Generated by GitHub Copilot on 2026-01-14
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0015_alter_perfilusuario_oficina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriedocumental',
            name='codigo_trd',
            field=models.CharField(blank=True, help_text='Código TRD de la serie', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subseriedocumental',
            name='codigo_trd',
            field=models.CharField(blank=True, help_text='Código TRD de la subserie', max_length=255, null=True),
        ),
    ]
