# Generated by Django 5.0.14 on 2026-01-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0016_remove_unique_codigo_trd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficinaproductora',
            name='codigo_trd',
            field=models.CharField(blank=True, help_text='Código TRD de la oficina (solo el número, ej: 300)', max_length=255, null=True),
        ),
    ]
