# Generated by Django 5.0.14 on 2026-01-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0017_alter_oficinaproductora_codigo_trd'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodearchivo',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
