# Generated by Django 5.0.14 on 2026-01-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0018_add_fecha_edicion_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriedocumental',
            options={'ordering': ['codigo'], 'verbose_name': 'Serie Documental', 'verbose_name_plural': 'Series Documentales'},
        ),
        migrations.AddField(
            model_name='seriedocumental',
            name='oficinas_productoras',
            field=models.ManyToManyField(blank=True, help_text='Oficinas productoras (subprocesos) que utilizan esta serie documental', related_name='series_documentales', to='documentos.oficinaproductora'),
        ),
    ]
