# Generated by Django 5.0.14 on 2026-02-09 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0019_agregar_relacion_series_oficinas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodearchivo',
            name='editado_por',
            field=models.ForeignKey(blank=True, help_text='Último usuario que editó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_editados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrodearchivo',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
