# Generated by Django 5.0.14 on 2026-03-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0020_add_editado_por_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamodocumental',
            name='oficina_responsable',
            field=models.ForeignKey(blank=True, help_text='Oficina a la que se dirige la solicitud de préstamo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_responsables', to='documentos.oficinaproductora'),
        ),
    ]