# Generated by Django 5.0.14 on 2026-03-31 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0021_prestamodocumental_oficina_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prestamodocumental',
            name='documentos__estado_3ea9a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='prestamodocumental',
            name='documentos__solicit_09cbd2_idx',
        ),
        migrations.AlterField(
            model_name='prestamodocumental',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('ENTREGADO', 'Entregado'), ('PRESTAMO_ACTIVO', 'Préstamo Activo'), ('DEVOLUCION_SOLICITADA', 'Devolución Solicitada'), ('DEVUELTO', 'Devuelto'), ('REINTEGRADO', 'Reintegrado'), ('RECHAZADO', 'Rechazado'), ('RECHAZADO_USUARIO', 'Rechazado por Usuario'), ('VENCIDO', 'Vencido')], default='SOLICITADO', max_length=25),
        ),
        migrations.AddIndex(
            model_name='prestamodocumental',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='documentos__estado_ed1f62_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamodocumental',
            index=models.Index(fields=['solicitante', 'fecha_solicitud'], name='documentos__solicit_5cd088_idx'),
        ),
    ]
