# Generated by Django 5.0.14 on 2026-04-07 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0023_oficinaproductora_codigo_trd_comunicacion_interna'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDescargaPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('filtro_estado', models.CharField(blank=True, max_length=25, null=True)),
                ('filtro_tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('filtro_alerta', models.CharField(blank=True, max_length=40, null=True)),
                ('filtro_tipo_archivo', models.CharField(blank=True, max_length=40, null=True)),
                ('filtro_oficina', models.CharField(blank=True, max_length=255, null=True)),
                ('busqueda', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descargas_reportes_prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Descarga de Préstamo',
                'verbose_name_plural': 'Historiales de Descarga de Préstamos',
                'ordering': ['-fecha_descarga'],
            },
        ),
        migrations.AddIndex(
            model_name='historialdescargaprestamo',
            index=models.Index(fields=['anio', 'mes', 'fecha_descarga'], name='documentos_h_anio_0b8dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='historialdescargaprestamo',
            index=models.Index(fields=['usuario', 'fecha_descarga'], name='documentos_h_usuario_f70ff7_idx'),
        ),
    ]